### ISSUE TITLE
Typing missmatch

### ISSUE THREAD

**Issue by geomen888** [RobinBuschmann/sequelize-typescript-example#2]
yarn run v1.5.1
$ node --require ts-node/register index.ts

/home/user/PROJECTS/5555/sequelize-typescript-example/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
lib/models/Movie.ts (34,22): Class static side 'typeof Movie' incorrectly extends base class static side 'typeof Model'.
  Types of property 'scope' are incompatible.
    Type '(...args: any[]) => typeof Movie' is not assignable to type '{ <T>(this: NonAbstractTypeOfModel<T>, options?: string | string[] | ScopeOptions | WhereOptions<...'.
      Type 'typeof Movie' is not assignable to type 'NonAbstractTypeOfModel<any>'.
        Type 'typeof Movie' is not assignable to type 'NonAbstract<typeof Model>'.
          Types of property 'create' are incompatible.
            Type '(values?: any, options?: ICreateOptions) => Bluebird<Movie>' is not assignable to type '<T extends Model<T>>(this: new () => T,values?: FilteredModelAttributes<T> | undefined, options?...'.
              Type 'Bluebird<Movie>' is not assignable to type 'Bluebird<T>'.
                Type 'Movie' is not assignable to type 'T'. (2417)
    at getOutput (/home/user/PROJECTS/5555/sequelize-typescript-example/node_modules/ts-node/src/index.ts:307:15)
    at /home/user/PROJECTS/5555/sequelize-typescript-example/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/home/user/PROJECTS/5555/sequelize-typescript-example/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/home/user/PROJECTS/5555/sequelize-typescript-example/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:660:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/user/PROJECTS/5555/sequelize-typescript-example/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c node --require ts-node/register index.ts
Directory: /home/user/PROJECTS/5555/sequelize-typescript-example
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/user/PROJECTS/5555/sequelize-typescript-example/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
user@user-VPCX11Z1R:~/PROJECTS/5555/sequelize-typescript-example$

**Comment by RobinBuschmann** [comment]
Hey @geomen888 thanks for reporting. Are you using this repo as it is or did you changed something? I'm asking because I couldn't reproduce it with the current state of this repo.

**Comment by geomen888** [comment]
Thanks for prompt feedback I'm using your example in original. I download it in case to study sequelize-typescript module. No changes have been made before error appears by me. I'm toggle strictNullChecks but it does not affect the error. Thank U 



Kind Regards Eugene 

Thursday, April 12, 2018, 18:20 +0300 from notifications@github.com  <notifications@github.com>:

**Comment by RobinBuschmann** [comment]
OK, I found something. This seems to be an issue with the node_modules yarn installs. The sequelize typings have a dependency on any bluebird typings `@types/bluebird@*` and sequelize-typescript do have a dependency on a specific version `@types/bluebird@3.5.18`. Since no other library has a dependency on bluebird, only `@types/bluebird@3.5.18` should be installed. But yarn installs two versions of bluebird, that conflict with each other. For now I can only suggest to use `npm` instead of `yarn`.

**Comment by geomen888** [comment]
Robin U are number One! With npm it's workable. So, pls add some comments to U repo to avoid using Yarn. Thank U


Kind Regards Eugene 

Thursday, April 12, 2018, 18:52 +0300 from notifications@github.com  <notifications@github.com>:
