### ISSUE TITLE
Default value doesn't appear to be recalculated after each insert

### ISSUE THREAD

**Issue by MarkusAnthony** [RobinBuschmann/sequelize-typescript-example#6]
When creating a new record it appears that the id is not being regenerated each time.

Model:

     export class MyDefinition extends Model<MyDefinition> {

       @Default(uuid.v4())
       @AllowNull(false)
       @PrimaryKey
       @Column
       id: string;

       @Column
       name: string;
     }

DTO:

     export class CreateMyDefDto {
         readonly name: string;
     }

Service:

    async create(dto: CreateMyDefDto): Promise<any> {
        return await this.MYDEF_REPOSITORY.create<MyDefinition>(dto);
    }

It appears that the same uuid that is generated the first time continues to be used. I am assuming that the default value is assumed to be a constant?

**Comment by RobinBuschmann** [comment]
Hey @MarkusAnthony, this is because with `uuid.v4()` you create one UUID and pass it to the @Default annotation. In order to give sequelize the ability to create every time a new UUID, you have to pass the function itself:
```ts
@Default(uuid.v4) // <-- without ()
```

Hope this helps!

**Comment by MarkusAnthony** [comment]
Great, thanks!
